
export const categories = [
  { cate: "all", category_id: "all",},
  { cate: "nutrition", category_id: "nutrition", },
  { cate: "fitness", category_id: "fitness", },
  { cate: "sleep", category_id: "sleep", },
  { cate: "parenting", category_id: "parenting",},
  { cate: "weight loss", category_id: "weight-loss", },
  { cate: " skincare", category_id: "skincare", },
  { cate: "mental health", category_id: "mental-health",  },
  { cate: "men's health", category_id: "mens-health", },
  { cate: "sexual health", category_id: "sexual-health", },
  { cate: "women's health", category_id: "womens-health", },
  { cate: "eye health", category_id: "eye-health", },
  { cate: "heart health", category_id: "heart-health",},
  { cate: "oral health", category_id: "oral-health", },
  { cate: "human biology", category_id: "human-biology",},
  { cate: "meditation", category_id: "meditation", },
  { cate: "spirituality", category_id: "spirituality", },
  // { cate: "recovery", category_id: "recovery},
];
