[build]
  command = "npm run build"
  functions = "functions"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "SAMEORIGIN"